### ISSUE TITLE
Feedback , and added installation process for some other people who would face the same issue

### ISSUE THREAD

**Issue by codeitlikemiley** [ant-vel/Installer#2]
installation process
git clone 
composer install
cp .example.env .env
php artisan key:generate
php artisan migrate --seed
bower install

few things need to be added is google Api for captcha ,
well thats is not a big deal to be added

links not working
https://antvel.app/summary
https://antvel.app/user/orders/placeOrder/cart

local assets for images , not part of repo, maybe change it to factory image for the database seeder

**Comment by gocanto** [comment]
Well, these are the things I still need to figure out. For example: 

- google keys need to be added by developers because they are linked to their google console keys. 

- Images are located in the main app, you might want to clone that repo because it is the one up to date (ant-vel/App) 

- assets are pulled in by bower 

- those routes you mentioned about are new ones served by the main app. So you might eant to clear your routes cache. 

I am opened for suggestions. 

:)

**Comment by gocanto** [comment]
This bug was fixed with the latest releases which can be found on https://github.com/ant-vel/Installer/releases/tag/1.0.5

Also, the readme file was updated with some of the steps to be executed by the user when installing the app throughout the ```installer```

Thanks for testing.

Remember to keep me posted with your feedback.
